name: dotnet

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        dotnet: [8.0.100]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Install wasm-tools
      run: dotnet workload install wasm-tools

    - name: Restore Tools
      run: dotnet tool restore    
    - name: Restore Dependencies
      run: dotnet paket restore
    - name: Build and Test
      run: dotnet fake run build.fsx
