name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macOS-latest]
        dotnet: [3.1.302]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Install libgdiplus on macOS
      if: matrix.os == 'macOS-latest'
      run: brew install mono-libgdiplus

    - name: Build Windows
      if: matrix.os == 'windows-latest'
      run: .\build.cmd
    - name: Build macOs
      if: matrix.os != 'windows-latest'
      run: ./build.sh
