name: Release

on: 
  workflow_dispatch:
    inputs:
      username:
        description: Github username of the person triggering the release
        default: "sergey-tihon"
        required: true

jobs:
  release:
    # this workflow is the same as the build workflow, up until artifact upload + publish
    runs-on: windows-latest

    steps:
    # manual triggers are detached HEADs, so we need to checkout the branch
    # to actually create + push a commit later on in the workflow
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Restore Tools
      run: dotnet tool restore    
    - name: Restore Dependencies
      run: dotnet paket restore  
    - name: Install wasm-tools
      run: dotnet workload install wasm-tools

    - name: Publish Blazor WASM
      run: dotnet publish -c Release src/MinMe.WebAssembly/MinMe.WebAssembly.csproj 
    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: src/MinMe.WebAssembly/bin/Release/net6.0/publish/wwwroot
        force_orphan: true